sed -i "s/nemiver-/nmv-/g" $@
sed -i "s/nemiverp/nemiver/g" $@
sed -i "s/GD++/Nemiver/g" $@
sed -i "s/gd++/nemiver/g" $@
sed -i "s/gdpp/nemiver/g" $@
sed -i "s/gdp-/nemiver/g" $@
sed -i "s/gdp/nemiver/g" $@
sed -i "s/GDPLUSPLUS/NMV/g" $@
sed -i "s/GDP_/NEMIVER_/g" $@
sed -i "s/GDPP/NEMIVER/g" $@
